export const allLegendaryNames: string[] = [
  "Abbess",
  "Acelin the Stalwart",
  "Acrizia",
  "Admiral Blacktusk",
  "Ailil",
  "Alatreon Blademaster",
  "Aleksandr the Sharpshooter",
  "Alice the Wanderer",
  "Alsgor Crimsonhorn",
  "Altan",
  "Amoch the First Satrap",
  "Angar",
  "April ONeil",
  "Aragaz Wyldking",
  "Arashi the Riptide",
  "Aratheia Corpseflower",
  "Arbiter",
  "Archbishop Pinthroy",
  "Aria the Golden Hope",
  "Arix",
  "Armanz the Magnificent",
  "Arnorn the Shining",
  "Artak",
  "Astralith",
  "Astralon",
  "Authoratrix Lamasu",
  "Ba Satha",
  "Bad-el-Kazar",
  "Baerd the Broad",
  "Balar the Lost",
  "Bambus Fourleaf",
  "Baron",
  "Basileus Roanas",
  "Basim Ibn Ishaq",
  "Bayek",
  "Belanor",
  "Belletar Mage Slayer",
  "Belz the Reckoner",
  "Big Un",
  "Bivald of the Thorn",
  "Black Knight",
  "Bladechorister Caldor",
  "Blind Seer",
  "Blizaar the Howler",
  "Bloodgorged",
  "Bolint Freewalker",
  "Boragar the Elder",
  "Brakus the Shifter",
  "Brewguard Jeroboam",
  "Bystophus",
  "Candraphon",
  "Caoilte the Asharrow",
  "Cardiel",
  "Cecilia the Red Hope",
  "Celendiel the Opal Guardian",
  "Chaagur",
  "Chalco the Blind",
  "Cheshire Cat",
  "Chronicler Adelyn",
  "Cillian the Lucky",
  "Claidna",
  "Cleopterix",
  "Corvis the Corruptor",
  "Countess Lix",
  "Craklin the Blackened",
  "Crohnam",
  "Cromax Moonblood",
  "Cruetraxa",
  "Crypt-King Graal",
  "Cupidus",
  "Danag Skullreap",
  "Deliana",
  "Diamant Coppercoin",
  "Donatello",
  "Dorothy Gale",
  "Dracomorph",
  "Drexthar Bloodtwin",
  "Drokgul the Gaunt",
  "Duchess Lilitu",
  "Dune Herald Zaharis",
  "Dune Lord Greggor",
  "Edward Kenway",
  "Elder Skarg",
  "Elegaius",
  "Elenaril",
  "Elva Autumnborn",
  "Emic Trunkheart",
  "Eostrid Dreamsong",
  "Errol",
  "Esme the Dancer",
  "Ezio Auditore",
  "Falmond Mournsword",
  "Fatalis Blademaster",
  "Firrol the Barkhorn",
  "First Ax Tuskkor",
  "Folan Silverhart",
  "Foli",
  "Fortus",
  "Freyja Fateweaver",
  "Fu-Shan",
  "Fyna Blade of Aravia",
  "Gaellut Son of the Pact",
  "Gaius the Gleeful",
  "Gamuran",
  "Gaspard the Accused",
  "Genzin",
  "Georgid the Breaker",
  "Ghostborn",
  "Giath the Truthshield",
  "Ginro the Stork",
  "Glaicad of the Meltwater",
  "Gliseah Soulguide",
  "Glorious Pallas",
  "Gnishak Verminlord",
  "Gnut",
  "Goffred Brassclad",
  "Gomlok Skyhide",
  "Graazur Irongut",
  "Gracchos Turn Drake",
  "Grand Oak Padraig",
  "Granyt Doorkeep",
  "Greathoof Loriaca",
  "Greenwarden Ruarc",
  "Gretel Hagbane",
  "Grohak the Bloodied",
  "Gronjarr",
  "Grugtha Darkseer",
  "Gurgoh the Augur",
  "Gurptuk Moss-Beard",
  "Guurda Bogbrew",
  "Gwyndolin the Silent",
  "Haggibah the Nestmaid",
  "Hakkorhn Smashlord",
  "Hansel Witchhunter",
  "Harima",
  "Harvest Jack",
  "He-Man",
  "Hegemon",
  "Helicath",
  "Helior",
  "Hephraak",
  "High Keeper Prysma",
  "Highmother Maud",
  "Hilvi the Rime Called",
  "Holguk of the Hallowsights",
  "Holsring",
  "Hurndig",
  "Ignatius",
  "Inithwe Bloodtwin",
  "Iron Brago",
  "Ishiyama the Immovable",
  "Ithos",
  "Iudex Artor",
  "Jagg Bonesaw",
  "Jetni the Giant",
  "Jingwon",
  "Jintoro",
  "Kaja the Wry",
  "Kalvalax",
  "Kantra the Cyclone",
  "Karato Foxhunter",
  "Karilon the Ringer",
  "Kassandra",
  "Kawn Branchbreaker",
  "Keberon the Underflame",
  "Keeyra the Watcher",
  "Kerin the Harvester",
  "Khamir Scald Eye",
  "Khoronar",
  "King Gallcobar",
  "King Garog",
  "Klaazag Keyhulk",
  "Knave of Hearts",
  "Knosson the Bronze Bull",
  "Konstantin the Dayborn",
  "Korugar Death-Bell",
  "Kosk of Two Skins",
  "Kreela Witch-Arm",
  "Krisk the Ageless",
  "Krokhad the Throatripper",
  "KrokMar the Devourer",
  "Kroz Wallbreaker",
  "Kyoku",
  "Lady Kimi",
  "Lady Noelle",
  "Lady of Ireth",
  "Lanakis the Chosen",
  "Legate Teox",
  "Leminisi the Gold Wing",
  "Leonardo",
  "Leorius the Proud",
  "Little Miss Annie",
  "Loki the Deceiver",
  "Lonatharil",
  "Longbeard",
  "Lord Champfort",
  "Lord Entertainer Fabian",
  "Lord Shazar",
  "Losan KLeth",
  "Lugan the Steadfast",
  "Lydia the Deathsiren",
  "Lysanthir Beastbane",
  "Lyssandra",
  "Mad Hatter",
  "Maranix",
  "Marichka the Unbreakable",
  "Marius the Gallant",
  "Martyr",
  "Masahiro the Bell Monk",
  "MaShalled",
  "Mathias Blackflail",
  "Matriarch Zarguna",
  "Maulie Tankard",
  "Mavara the Web Diviner",
  "Michelangelo",
  "Michinaki",
  "Mighty Ukko",
  "Minaya",
  "Mithrala Lifebane",
  "Miyoko Flower of Yakai",
  "Modo of the Peal",
  "Morrigaine",
  "Mortu-Macaab",
  "Mother Cybele",
  "Mountain King",
  "Nari the Lucky",
  "Narma the Returned",
  "Nekhret the Great",
  "Nekmo Thaar",
  "Nethril",
  "Niamhe Spear of Nyresa",
  "Ninja",
  "Nobel",
  "Noct the Paralyzer",
  "Nogdar the Headhunter",
  "Noldua the Gloaming",
  "Norog",
  "Odin Faefather",
  "Oella",
  "Onryo Ieyasu",
  "Opardin Clanfather",
  "Osgrun the Defiler",
  "Owein Winterflame",
  "Ozilda the Wicked",
  "Packmaster Shyek",
  "Pelagus the Wavewalker",
  "Pelops the Victor",
  "Pheidi Tealcrest",
  "Phemo the Shepherd",
  "Pontiff Augustin",
  "Praeva the Slitherer",
  "Predator",
  "Prince Kymar",
  "Pythion",
  "Pyxniel",
  "Queen Eva",
  "Queen of Hearts",
  "Quintus the Triumphant",
  "R. Nergigante Archer",
  "Rae",
  "Raf-Matab",
  "Ragash",
  "Raglin",
  "Rakka Viletide",
  "Ramantu Drakesblood",
  "Raphael",
  "Rathalos Blademaster",
  "Razelvarg",
  "Rhaia the Mourned",
  "Rhazin Scarhide",
  "Richtoff the Bold",
  "Riho Bonespear",
  "Robar",
  "Ronda",
  "Roric Wyrmbane",
  "Roshcard the Tower",
  "Rotos the Lost Groom",
  "Roxam",
  "Royal Huntsman",
  "Ruel the Huntmaster",
  "Saito",
  "Samar Gemcursed",
  "Samson the Masher",
  "Sanguine Maria",
  "Scyl of the Drakes",
  "Searsha the Charred",
  "Senna Amberheart",
  "Septimus",
  "Sethallia",
  "Shamrock",
  "Shemnath",
  "Shirimani",
  "Shredder",
  "Shu-Zhen the Valorous",
  "Sicia Flametongue",
  "Sigmund the Highshield",
  "Siphi the Lost Bride",
  "Sir Nicholas",
  "Skartorsis",
  "Skeletor",
  "Skorid the Halfspawn",
  "Skull Lord Var-Gall",
  "Sniktraak",
  "Solanar the Gleaming",
  "Soulless",
  "Staltus Dragonbane",
  "Stokk the Broken",
  "Storm Herald Hekaton",
  "Strategos Islin",
  "Sulfuryion",
  "Sun Wukong",
  "Supreme Athel",
  "Supreme Elhain",
  "Supreme Galek",
  "Supreme Kael",
  "Suzerain Katonn",
  "Swarmspeaker Zyclic",
  "Sydax King Killer",
  "Talenna Soulseer",
  "Taras the Fierce",
  "Tatsu",
  "Tatura Rimehide",
  "Teela Goremane",
  "Tekteon Fissureflesh",
  "Teodor the Savant",
  "Tetsuya the Deliverer",
  "Teumesia",
  "Thayla Hammerhorn",
  "The Cowardly Lion",
  "The Incarnate",
  "The Scarecrow",
  "The Tin Woodman",
  "Thea the Tomb Angel",
  "Tholin Foulbeard",
  "Thor Faehammer",
  "Thralia She Who Stands",
  "Timit the Fool",
  "Titus Blackplume",
  "Togron the Conjoined",
  "Tomb Lord",
  "Tormin the Cold",
  "Tramaria",
  "Tribune Herakletes",
  "Truath",
  "Trunda Giltmallet",
  "Tuhanarak",
  "Turvold",
  "Tyrant Ixlimor",
  "Ugir the Wyrmeater",
  "Ultan of the Shell",
  "Ultimate Deathknight",
  "Underpriest Brogni",
  "Urost the Soulcage",
  "Ursuga Warcaller",
  "Uzol of the Jade",
  "Valkanen",
  "Valkyrie",
  "Vallaryn the Equalizer",
  "Varkos Headsplitter",
  "Varl the Destroyer",
  "Vasal of the Seal",
  "Vault Keeper Wixwell",
  "Venalicia Thrallmother",
  "Venus",
  "Vergumkaar",
  "Versulf the Grim",
  "Vestele Riverthorn",
  "Visix the Unbowed",
  "Vitrius the Anointed",
  "Vizier Ovelis",
  "Vizug the Noxious",
  "Vlad the Nightborn",
  "Vulkanos Fumor",
  "Walking Tomb Dreng",
  "Wallmaster Othorion",
  "War Mother",
  "Warchief",
  "Warlord",
  "Wight King Narses",
  "Wight Queen Ankora",
  "Wurlim Frostking",
  "Wythir the Crowned",
  "Xalgaze Fangwall",
  "Xena Warrior Princess",
  "Xenomorph",
  "Xiloco the Encrusted",
  "Yakarl the Scourge",
  "Yannica",
  "Yncensa Grail-bearer",
  "Yoshi the Drunkard",
  "Yukimasa Demon of Ice",
  "Yumeko",
  "Zavia",
  "Zinogre Blademaster"
];

