import { useEffect, useState } from 'react';
import { api } from './api';
import './offer-screens.css';

export default function OfferScreens({offerId}:{offerId:string}){
  const [data,setData]=useState<{title:string;images:string[]}|null>(null);
  const [error,setError]=useState('');
  const [available,setAvailable]=useState<{id:string;title:string;count:number;status:string}[]>([]);
  const [selected,setSelected]=useState(0);
  const [zoom,setZoom]=useState(false);
  useEffect(()=>{let active=true;setData(null);setError('');setAvailable([]);setSelected(0);api.offerScreens(offerId).then(value=>{if(active)setData(value)}).catch(async reason=>{if(!active)return;setError(reason instanceof Error?reason.message:'Не удалось открыть скриншоты');if(reason instanceof Error&&reason.message==='Оффер не найден'){try{const list=await api.offerScreensIndex();if(active)setAvailable(list)}catch{}}});return()=>{active=false}},[offerId]);
  return <main className="offer-screens"><a href="/" className="screens-back">← Назад</a><div className="screens-heading"><span>ОФФЕР / СКРИНШОТЫ</span><h1>{data?.title||'Просмотр скриншотов'}</h1><p>{data?`Все ${data.images.length} снимков в одной галерее. Нажмите на большой снимок, чтобы увеличить.`:'Галерея доступна только администраторам.'}</p></div>{error&&<div className="screens-error">{error==='Оффер не найден'?'Ссылка на этот оффер устарела или он был удалён. Выберите актуальный оффер ниже.':error}</div>}{available.length>0&&<div className="screens-available"><h2>Офферы со скриншотами</h2>{available.map(item=><a key={item.id} href={`/?screens=${encodeURIComponent(item.id)}`}>{item.title}<span>{item.count} снимков · {item.status==='pending'?'на проверке':'опубликован'}</span></a>)}</div>}{error==='Оффер не найден'&&available.length===0&&<p className="screens-loading">Актуальных офферов со скриншотами нет. Если снимки не сохранились в томе Railway, их потребуется загрузить повторно.</p>}{!data&&!error&&<p className="screens-loading">Загружаем галерею…</p>}{data&&<><button type="button" className="screens-main" onClick={()=>setZoom(true)}>{data.images.length>0&&<img src={data.images[selected]} alt={`Скриншот ${selected+1} из ${data.images.length}`}/>}</button><div className="screens-controls"><button type="button" disabled={selected===0} onClick={()=>setSelected(selected-1)}>← Предыдущий</button><span>{selected+1} / {data.images.length}</span><button type="button" disabled={selected>=data.images.length-1} onClick={()=>setSelected(selected+1)}>Следующий →</button></div><div className="screens-grid">{data.images.map((src,index)=><button key={index} type="button" className={selected===index?'active':''} onClick={()=>{setSelected(index);document.querySelector('.screens-main')?.scrollIntoView({behavior:'smooth',block:'start'})}} aria-label={`Открыть скриншот ${index+1}`}><img src={src} alt={`Миниатюра ${index+1}`} loading="lazy"/><span>{index+1}</span></button>)}</div>{zoom&&<div className="image-lightbox" role="dialog" aria-modal="true" onClick={()=>setZoom(false)}><button type="button" aria-label="Закрыть" onClick={()=>setZoom(false)}>×</button><img src={data.images[selected]} alt={`Скриншот ${selected+1}`} onClick={event=>event.stopPropagation()}/><span>{selected+1} / {data.images.length}</span></div>}</>}</main>;
}
